server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/java-06-springboot
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Cuong211998
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8080/auth/realms/VSS

keycloak:
  realm: VSS
  auth-server-url: http://localhost:8080/auth
  resource: CRM-backend-test
  public-client: true
  bearer-only: true
#https://www.youtube.com/watch?v=La082JsJoH4

